replicaCount: 1

image:
  repository: codercom/code-server
  tag: '4.90.2'
  pullPolicy: Always

imagePullSecrets: []
#  - name: registry-creds

nameOverride: ""
fullnameOverride: ""
hostnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
#  fsGroup: 2000

priorityClassName: ""

service:
  loadBalancerIP: <IP ADDRESS OF LOAD BALANCER>
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: code-server.example.com
      paths:
        - /
  ingressClassName: "traefik"
  tls: []
#    - secretName: code-server
#      hosts:
#        - code-server.example.com

extraArgs: []

extraVars: []
#  - name: DISABLE_TELEMETRY
#    value: "true"

volumePermissions:
  enabled: true
  securityContext:
    runAsUser: 0

securityContext:
  enabled: true
  fsGroup: 1000
  runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 2Gi
  annotations: {}

lifecycle:
  enabled: false

extraContainers: |
#  - name: docker-dind
#    image: docker:19.03-dind
#    imagePullPolicy: IfNotPresent
#    resources:
#      requests:
#        cpu: 250m
#        memory: 256M
#    securityContext:
#      privileged: true
#    procMount: Default
#    env:
#      - name: DOCKER_TLS_CERTDIR
#        value: ""
#      - name: DOCKER_DRIVER
#        value: "overlay2"

extraInitContainers: |
#  - name: customization
#    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
#    imagePullPolicy: IfNotPresent
#    env:
#      - name: SERVICE_URL
#        value: https://open-vsx.org/vscode/gallery
#      - name: ITEM_URL
#        value: https://open-vsx.org/vscode/item
#    command:
#      - sh
#      - -c
#      - |
#        code-server --install-extension ms-python.python
#        code-server --install-extension golang.Go
#    volumeMounts:
#      - name: data
#        mountPath: /home/coder

extraSecretMounts: []

extraVolumeMounts: []

extraConfigmapMounts: []

extraPorts: []
